#### Q1 You have to handle commonly occurring EXCEPTIONS by using exception handling programing. To get
information about selenium Exceptions. You may visit following links:
1. https://selenium-python.readthedocs.io/api.html
2. https://www.guru99.com/exception-handling-selenium.html
3. https://stackoverflow.com/questions/38022658/selenium-python-handling-no-such-elementexception/38023345

#### 1. Scrape the details of most viewed videos on YouTube from Wikipedia:
Url = https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos/
You need to find following details:

A) Rank

B) Name

C) Artist

D) Upload date

E) Views

In [31]:
#importing all libraries
import selenium
import pandas as pd
import time
from bs4 import BeautifulSoup

#Import selenium webdriver 
from selenium import webdriver

#Import required Exceptions which needs to handled
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException, ElementNotInteractableException

#Import requests
import requests

#Importing regex
import re

#Import support drivers
import time
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By

#Import Time Out Exception
from selenium.common.exceptions import TimeoutException
from datetime import datetime

#Suppress warnings for a clean notebook
import warnings
warnings.filterwarnings('ignore')

In [10]:
# connect to the webdriver
driver = webdriver.Chrome(r"C:\Users\admin\Downloads\chromedriver_win32 (1)\chromedriver.exe")
time.sleep(3)

# get the url
url = "https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos"
driver.get(url)

# creating empty list for scrapping data
rank = []
name = []
artist = []
upload_data = []
view = []

In [14]:
rank=[]
try:
    ranks=driver.find_elements_by_xpath('//table[@class="wikitable sortable jquery-tablesorter"][1]/tbody/tr/td[1]')
    for i in ranks:
        rank.append(i.text)
except NoSuchElementException:
    rank.append('-')
except StaleElementReferenceException:
    rank.append('-')

In [15]:
name = []
try:
    names=driver.find_elements_by_xpath('//table[@class="wikitable sortable jquery-tablesorter"][1]/tbody/tr/td[2]')
    for i in names:
        name.append(i.text)
except NoSuchElementException:
    name.append('-')
except StaleElementReferenceException:
    name.append('-')

In [16]:
artist = []
try:
    artists= driver.find_elements_by_xpath('//table[@class="wikitable sortable jquery-tablesorter"][1]/tbody/tr/td[3]')
    for i in artists:
        artist.append(i.text)
        
except NoSuchElementException:
    artist.append('-')

except StaleElementReferenceException:
    artist.append('-')

In [18]:
upload_data = []

try:
    data = driver.find_elements_by_xpath('//table[@class="wikitable sortable jquery-tablesorter"][1]/tbody/tr/td[3]')
    for i in data:
        upload_data.append(i.text)
        
except NoSuchElementException:
    upload_data.append('-')
    
except StaleElementReferenceException:
     upload_data.append('-')

In [19]:
view = []

try:
    views = driver.find_elements_by_xpath('//table[@class="wikitable sortable jquery-tablesorter"][1]/tbody/tr/td[3]')
    for i in views:
        view.append(i.text)
        
except NoSuchElementException:
    view.append('-')
    
except StaleElementReferenceException:
    view.append('-')

In [21]:
youtube_videos = pd.DataFrame({})
youtube_videos['Rank'] = rank
youtube_videos['Name'] = name
youtube_videos['Artist']= artist
youtube_videos['Upload_Data']=upload_data
youtube_videos['View'] = view
youtube_videos

,Rank,Name,Artist,Upload_Data,View
0,1.,"""Baby Shark Dance""[22]",Pinkfong Kids' Songs & Stories,Pinkfong Kids' Songs & Stories,Pinkfong Kids' Songs & Stories
1,2.,"""Despacito""[24]",Luis Fonsi,Luis Fonsi,Luis Fonsi
2,3.,"""Johny Johny Yes Papa""[25]",LooLoo Kids,LooLoo Kids,LooLoo Kids
3,4.,"""Shape of You""[26]",Ed Sheeran,Ed Sheeran,Ed Sheeran
4,5.,"""See You Again""[27]",Wiz Khalifa,Wiz Khalifa,Wiz Khalifa
5,6.,"""Bath Song""[30]",Cocomelon – Nursery Rhymes,Cocomelon – Nursery Rhymes,Cocomelon – Nursery Rhymes
6,7.,"""Learning Colors – Colorful Eggs on a Farm""[31]",Miroshka TV,Miroshka TV,Miroshka TV
7,8.,"""Masha and the Bear – Recipe for Disaster""[32]",Get Movies,Get Movies,Get Movies
8,9.,"""Uptown Funk""[33]",Mark Ronson,Mark Ronson,Mark Ronson
9,10.,"""Gangnam Style""[34]",Psy,Psy,Psy
10,11.,"""Phonics Song with Two Words""[36]",ChuChu TV,ChuChu TV,ChuChu TV
11,12.,"""Dame Tu Cosita""[37]",El Chombo,El Chombo,El Chombo
12,13.,"""Sugar""[38]",Maroon 5,Maroon 5,Maroon 5
13,14.,"""Sorry""[39]",Justin Bieber,Justin Bieber,Justin Bieber
14,15.,"""Roar""[40]",Katy Perry,Katy Perry,Katy Perry
15,16.,"""Counting Stars""[41]",OneRepublic,OneRepublic,OneRepublic
16,17.,"""Thinking Out Loud""[42]",Ed Sheeran,Ed Sheeran,Ed Sheeran
17,18.,"""Wheels on the Bus""[43]",Cocomelon – Nursery Rhymes,Cocomelon – Nursery Rhymes,Cocomelon – Nursery Rhymes
18,19.,"""Dark Horse""[44]",Katy Perry,Katy Perry,Katy Perry
19,20.,"""Faded""[45]",Alan Walker,Alan Walker,Alan Walker
20,21.,"""Girls Like You""[46]",Maroon 5,Maroon 5,Maroon 5
21,22.,"""Shake It Off""[47]",Taylor Swift,Taylor Swift,Taylor Swift
22,23.,"""Lean On""[48]",Major Lazer,Major Lazer,Major Lazer
23,24.,"""Bailando""[49]",Enrique Iglesias,Enrique Iglesias,Enrique Iglesias
24,25.,"""Let Her Go""[50]",Passenger,Passenger,Passenger
25,26.,"""Mi Gente""[51]",J Balvin,J Balvin,J Balvin
26,27.,"""Axel F""[52]",Crazy Frog,Crazy Frog,Crazy Frog
27,28.,"""Perfect""[53]",Ed Sheeran,Ed Sheeran,Ed Sheeran
28,29.,"""Waka Waka (This Time for Africa)""[54]",Shakira,Shakira,Shakira
29,30.,"""Hello""[55]",Adele,Adele,Adele

#### 2. Scrape the details team India’s international fixtures from bcci.tv.
Url = https://www.bcci.tv/.
You need to find following details:
A) Match title (I.e. 1st ODI)

B) Series

C) Place

D) Date

E) Time

Note: - From bcci.tv home page you have reach to the international fixture page through code.

In [95]:
#importing required libraries
import pandas as pd
import time
import selenium
from selenium import webdriver
from selenium.common.exceptions import NoSuchElementException, StaleElementReferenceException

In [96]:
# connect to the webdriver
driver = webdriver.Chrome(r"C:\Users\admin\Downloads\chromedriver_win32 (1)\chromedriver.exe")
time.sleep(4)

#get the url
url = "https://www.bcci.tv/"
driver.get(url)
time.sleep(3)

# clicking the options
options=driver.find_element_by_xpath("//div[@class='navigation__drop-down drop-down drop-down--reveal-on-hover']")
options.click()
time.sleep(3)

#clicking the fixtures
fixtures=driver.find_element_by_xpath("//a[@class='navigation__link navigation__link--in-drop-down']")
fixtures.click()

In [97]:
#creating empty list for scraping data
Match_title=[]
Series=[]
Place=[]
Date=[]
Time=[]

# scraping match title
title = driver.find_elements_by_xpath("//strong[@class='fixture__name fixture__name--with-margin']")
for i in title:       
    if i.text is None :
        Match_title.append("--") 
    else:
        Match_title.append(i.text)

In [99]:
# scraping series
series = driver.find_elements_by_xpath("//span[@class='u-unskewed-text fixture__tournament-label u-truncated']")
for i in series:       
    if i.text is None :
        Series.append("--") 
    else:
        Series.append(i.text)

In [100]:
# scraping Place
place = driver.find_elements_by_xpath("//p[@class='fixture__additional-info']//span")
for i in place:       
    if i.text is None :
        Place.append("--") 
    else:
        Place.append(i.text)

In [101]:
# scraping Date
date = driver.find_elements_by_xpath("//span[@class='fixture__date']")
for i in date:       
    if i.text is None :
        Date.append("--") 
    else:
        Date.append(i.text)

In [102]:
#creating empty list for month
Month=[]
# scraping Month
month = driver.find_elements_by_xpath("//span[@class='fixture__month']")
for i in month:       
    if i.text is None :
        Month.append("--") 
    else:
        Month.append(i.text)      #optional scraping for Month

In [103]:
#creating empty list for day
Day=[]
# scraping Day
day = driver.find_elements_by_xpath("//span[@class='fixture__day']")
for i in day:       
    if i.text is None :
        Day.append("--") 
    else:
        Day.append(i.text)      #optional scraping of Day

In [104]:

# scraping Time
time = driver.find_elements_by_xpath("//span[@class='fixture__time']")
for i in time:       
    if i.text is None :
        Time.append("--") 
    else:
        Time.append(i.text)

In [105]:
# creating the dataframe from the scraped data
df=pd.DataFrame({"Match_title":Match_title,"Series":Series,"Place":Place,"Date":Date,"Month":Month,"Day":Day,"Time":Time})
df

,Match_title,Series,Place,Date,Month,Day,Time
0,4th Test,ENGLAND V INDIA 2021,"The Oval, London",02,SEPTEMBER,Thursday,15:30 IST
1,5th Test,ENGLAND V INDIA 2021,"Old Trafford, Manchester",10,SEPTEMBER,Friday,15:30 IST
2,Match 16,2021 ICC MEN'S T20 WORLD CUP,"Dubai International Cricket Stadium, Dubai",24,OCTOBER,Sunday,19:30 IST
3,Match 28,2021 ICC MEN'S T20 WORLD CUP,"Dubai International Cricket Stadium, Dubai",31,OCTOBER,Sunday,19:30 IST
4,Match 33,2021 ICC MEN'S T20 WORLD CUP,"Sheikh Zayed Cricket Stadium, Abu Dhabi",03,NOVEMBER,Wednesday,19:30 IST
5,Match 37,2021 ICC MEN'S T20 WORLD CUP,"Dubai International Cricket Stadium, Dubai",05,NOVEMBER,Friday,19:30 IST
6,Match 42,2021 ICC MEN'S T20 WORLD CUP,"Dubai International Cricket Stadium, Dubai",08,NOVEMBER,Monday,19:30 IST

#### Q3 Scrape the details of selenium exception from guru99.com.
Url = https://www.guru99.com/
You need to find following details:

A) Name

B) Description

Note: - From guru99 home page you have to reach to selenium exception handling page through code.

In [3]:
#importing required libraries
import pandas as pd
import time
import selenium
from selenium import webdriver
from selenium.common.exceptions import NoSuchElementException, StaleElementReferenceException

In [12]:
# connect to the webdriver
driver = webdriver.Chrome(r"C:\Users\admin\Downloads\chromedriver_win32 (1)\chromedriver.exe")
url = "https://www.guru99.com/"
driver.get(url)

In [13]:
sec=driver.find_element_by_xpath("//div[@class='srch']/span[8]/a")
sec.click()

In [14]:
se=driver.find_element_by_xpath("//table[@class='table'][5]/tbody/tr[34]/td[1]")
se.click()

In [15]:
Name = []
exc=driver.find_elements_by_xpath("//table[@class='table table-striped']/tbody/tr/td[1]")
Name=[]
for i in exc:
    Name.append(i.text)

In [16]:
Description = []
des=driver.find_elements_by_xpath("//table[@class='table table-striped']/tbody/tr/td[2]")
Description=[]
for i in des:
    Description.append(i.text)

In [17]:
Selenium_exception=pd.DataFrame({})
Selenium_exception["Name"]=Name
Selenium_exception["Description"]=Description

In [18]:
Selenium_exception.head()

,Name,Description
0,ElementNotVisibleException,This type of Selenium exception occurs when an...
1,ElementNotSelectableException,This Selenium exception occurs when an element...
2,NoSuchElementException,This Exception occurs if an element could not ...
3,NoSuchFrameException,This Exception occurs if the frame target to b...
4,NoAlertPresentException,This Exception occurs when you switch to no pr...

In [20]:
Selenium_exception.shape

(41, 2)

In [21]:
Selenium_exception=Selenium_exception[1:42]

In [22]:
Selenium_exception

,Name,Description
1,ElementNotSelectableException,This Selenium exception occurs when an element...
2,NoSuchElementException,This Exception occurs if an element could not ...
3,NoSuchFrameException,This Exception occurs if the frame target to b...
4,NoAlertPresentException,This Exception occurs when you switch to no pr...
5,NoSuchWindowException,This Exception occurs if the window target to ...
6,StaleElementReferenceException,This Selenium exception occurs happens when th...
7,SessionNotFoundException,The WebDriver is acting after you quit the bro...
8,TimeoutException,Thrown when there is not enough time for a com...
9,WebDriverException,This Exception takes place when the WebDriver ...
10,ConnectionClosedException,This type of Exception takes place when there ...
11,ElementClickInterceptedException,The command may not be completed as the elemen...
12,ElementNotInteractableException,This Selenium exception is thrown when any ele...
13,ErrorInResponseException,This happens while interacting with the Firefo...
14,ErrorHandler.UnknownServerException,Exception is used as a placeholder in case if ...
15,ImeActivationFailedException,This expectation will occur when IME engine ac...
16,ImeNotAvailableException,It takes place when IME support is unavailable.
17,InsecureCertificateException,Navigation made the user agent to hit a certif...
18,InvalidArgumentException,It occurs when an argument does not belong to ...
19,InvalidCookieDomainException,This happens when you try to add a cookie unde...
20,InvalidCoordinatesException,This type of Exception matches an interacting ...
21,InvalidElementStateExceptio,It occurs when command can’t be finished when ...
22,InvalidSessionIdException,This Exception took place when the given sessi...
23,InvalidSwitchToTargetException,This occurs when the frame or window target to...
24,JavascriptException,This issue occurs while executing JavaScript g...
25,JsonException,It occurs when you afford to get the session w...
26,NoSuchAttributeException,This kind of Exception occurs when the attribu...
27,MoveTargetOutOfBoundsException,It takes place if the target provided to the A...
28,NoSuchContextException,ContextAware does mobile device testing.
29,NoSuchCookieException,This Exception occurs when no cookie matching ...
30,NotFoundException,This Exception is a subclass of WebDriverExcep...
31,RemoteDriverServerException,This Selenium exception is thrown when the ser...
32,ScreenshotException,It is not possible to capture a screen.
33,SessionNotCreatedException,It happens when a new session could not be suc...
34,UnableToSetCookieException,This occurs if a driver is unable to set a coo...
35,UnexpectedTagNameException,Happens if a support class did not get a web e...
36,UnhandledAlertException,This expectation occurs when there is an alert...
37,UnexpectedAlertPresentException,It occurs when there is the appearance of an u...
38,UnknownMethodException,This Exception happens when the requested comm...
39,UnreachableBrowserException,This Exception occurs only when the browser is...
40,UnsupportedCommandException,This occurs when remote WebDriver does n’t sen...

#### 4. Scrape the details of State-wise GDP of India from statisticstime.com.
Url = http://statisticstimes.com

We have to find following details:

A) Rank

B) State

C) GSDP(19-20)

D) GSDP(18-19)

E) Share(2018)

F) GDP($ billion)

In [23]:
#importing required libraries
import pandas as pd
import time
import selenium
from selenium import webdriver
from selenium.common.exceptions import NoSuchElementException, StaleElementReferenceException

In [19]:
# connect to the webdriver
driver = webdriver.Chrome(r"C:\Users\admin\Downloads\chromedriver_win32 (1)\chromedriver.exe")
url = "http://statisticstimes.com"
driver.get(url)

In [24]:
#click on the economy and then on India from there
Economy_India=driver.find_element_by_xpath("//div[@class='navbar']/div[2]/div/a[3]")
driver.get(Economy_India.get_attribute('href'))

In [25]:
#click on the GDP of Indian states 
GDP_Indian_States=driver.find_element_by_xpath("//div[@style='float:left;background-color:seashell;width:400px;height:800px;']/ul/li[1]/a")
driver.get(GDP_Indian_States.get_attribute('href'))

In [26]:
#create an empty lists to store the scraping data
Rank=[] 
State=[] 
GSDP_Year_2019_to_Year_2020=[] 
GSDP_Year_2018_to_Year_2019=[] 
Share_Year_2018_to_2019=[] 
GDP_Dollar_Billion=[]

In [27]:
#create a function
rank = driver.find_elements_by_xpath('//table[@id="table_id"]/tbody/tr/td[1]')
for i in rank:
    Rank.append(i.text)
state = driver.find_elements_by_xpath('//table[@id="table_id"]/tbody/tr/td[2]')
for i in state:
    State.append(i.text)
gdsp_19_20 = driver.find_elements_by_xpath('//table[@id="table_id"]/tbody/tr/td[3]')
for i in gdsp_19_20:
    GSDP_Year_2019_to_Year_2020.append(i.text)
gdsp_18_19 = driver.find_elements_by_xpath('//table[@id="table_id"]/tbody/tr/td[4]')
for i in gdsp_18_19:
    GSDP_Year_2018_to_Year_2019.append(i.text)
share = driver.find_elements_by_xpath('//table[@id="table_id"]/tbody/tr/td[5]')
for i in share:
    Share_Year_2018_to_2019.append(i.text)
gdp_dollar = driver.find_elements_by_xpath('//table[@id="table_id"]/tbody/tr/td[6]')
for i in gdp_dollar:
    GDP_Dollar_Billion.append(i.text)

In [28]:
#create the dataframe from the scraped data
GSDP=pd.DataFrame({})
GSDP['Rank']=Rank 
GSDP['State']=State
GSDP['GSDP (Cr INR at Current prices) Year 2018-2019']=GSDP_Year_2018_to_Year_2019 
GSDP['GSDP (Cr INR at Current prices) Year 2019-2020']=GSDP_Year_2019_to_Year_2020 
GSDP['Share Year 2018-2019']=Share_Year_2018_to_2019 
GSDP['GDP ($ Billion)']=GDP_Dollar_Billion
GSDP

,Rank,State,GSDP (Cr INR at Current prices) Year 2018-2019,GSDP (Cr INR at Current prices) Year 2019-2020,Share Year 2018-2019,GDP ($ Billion)
0,1,Maharashtra,"2,632,792",-,13.94%,399.921
1,2,Tamil Nadu,"1,630,208","1,845,853",8.63%,247.629
2,3,Uttar Pradesh,"1,584,764","1,687,818",8.39%,240.726
3,4,Gujarat,"1,502,899",-,7.96%,228.290
4,5,Karnataka,"1,493,127","1,631,977",7.91%,226.806
5,6,West Bengal,"1,089,898","1,253,832",5.77%,165.556
6,7,Rajasthan,"942,586","1,020,989",4.99%,143.179
7,8,Andhra Pradesh,"862,957","972,782",4.57%,131.083
8,9,Telangana,"861,031","969,604",4.56%,130.791
9,10,Madhya Pradesh,"809,592","906,672",4.29%,122.977
10,11,Kerala,"781,653",-,4.14%,118.733
11,12,Delhi,"774,870","856,112",4.10%,117.703
12,13,Haryana,"734,163","831,610",3.89%,111.519
13,14,Bihar,"530,363","611,804",2.81%,80.562
14,15,Punjab,"526,376","574,760",2.79%,79.957
15,16,Odisha,"487,805","521,275",2.58%,74.098
16,17,Assam,"315,881",-,1.67%,47.982
17,18,Chhattisgarh,"304,063","329,180",1.61%,46.187
18,19,Jharkhand,"297,204","328,598",1.57%,45.145
19,20,Uttarakhand,"245,895",-,1.30%,37.351
20,21,Jammu & Kashmir,"155,956",-,0.83%,23.690
21,22,Himachal Pradesh,"153,845","165,472",0.81%,23.369
22,23,Goa,"73,170","80,449",0.39%,11.115
23,24,Tripura,"49,845","55,984",0.26%,7.571
24,25,Chandigarh,"42,114",-,0.22%,6.397
25,26,Puducherry,"34,433","38,253",0.18%,5.230
26,27,Meghalaya,"33,481","36,572",0.18%,5.086
27,28,Sikkim,"28,723","32,496",0.15%,4.363
28,29,Manipur,"27,870","31,790",0.15%,4.233
29,30,Nagaland,"27,283",-,0.14%,4.144
30,31,Arunachal Pradesh,"24,603",-,0.13%,3.737
31,32,Mizoram,"22,287","26,503",0.12%,3.385
32,33,Andaman & Nicobar Islands,-,-,-,-

#### 5. Scrape the details of trending repositories on Github.com.
Url = https://github.com/ You have to find the following details: A) Repository title B) Repository description C) Contributors count D) Language used

In [ ]:
#importing required libraries
import pandas as pd
import time
import selenium
from selenium import webdriver
from selenium.common.exceptions import NoSuchElementException, StaleElementReferenceException

In [29]:
# connect to the webdriver
driver = webdriver.Chrome(r"C:\Users\admin\Downloads\chromedriver_win32 (1)\chromedriver.exe")
url = "https://github.com/ "
driver.get(url)

In [32]:
#navigate to the trending option and click on it
trending=driver.find_element_by_xpath("/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details/div/ul[2]/li[3]/a")
try:
    trending.click()
except ElementNotInteractableException:
    driver.get(trending.get_attribute('href'))

#create an empty lists to store scraping data
Repository_Title=[]
Repository_Description=[] 
Contributors_Count=[] 
Language_Used=[]
urls=[]

In [33]:
#create a function
rep_title=driver.find_elements_by_xpath('//article[@class="Box-row"]/h1/a')
descriptions=driver.find_elements_by_xpath('//article[@class="Box-row"]/p')
for i in [rep_title,descriptions]:
    for j in i:
        if i ==rep_title:
            Repository_Title.append(j.text)
            urls.append(j.get_attribute('href'))
        if i==descriptions:
            Repository_Description.append(j.text)
for url in urls:
    driver.get(url)
    driver.implicitly_wait(3)
    div_list=driver.find_elements_by_xpath('//div[@class="BorderGrid BorderGrid--spacious"]/div')
    try:
        Contributors_Count.append(((div_list[-2].text).split())[1])
    except:
        Contributors_Count.append('-')
    try:
        Language_Used.append(((div_list[-1].text).split())[1::2])
    except:
        Language_Used.append('-')

#check the length of the scrape data        
print(len(Repository_Title),len(Repository_Description),len(Contributors_Count),len(Language_Used))

25 25 25 25

In [34]:
#create the dataframe from the scraped data
Repositoriy=pd.DataFrame({})
Repositoriy['Repository Title']=Repository_Title[0:23]
Repositoriy['Repository Description']=Repository_Description[0:23]
Repositoriy['Contributors Count']=Contributors_Count[0:23]
Repositoriy['Language Used']=Language_Used[0:23]
Repositoriy

,Repository Title,Repository Description,Contributors Count,Language Used
0,ClassmateLin / jd_scripts,Scripts,-,"[Python, Shell, Dockerfile]"
1,projectdiscovery / nuclei-templates,Community curated list of templates for the nu...,236,[Python]
2,public-apis / public-apis,A collective list of free APIs,882,"[Python, Shell]"
3,jina-ai / jina,Cloud-native neural search framework for 𝙖𝙣𝙮 k...,108,"[Python, HTML, Shell, Dockerfile, CSS, EJS, Ja..."
4,TencentARC / GFPGAN,GFPGAN aims at developing Practical Algorithms...,4,[Python]
5,microsoft / terminal,The new Windows Terminal and the original Wind...,297,"[C++, C#, C, PowerShell, PHP, Batchfile]"
6,doocs / jvm,🤗 JVM 底层原理最全知识总结,7,"[Java, JavaScript]"
7,withfig / autocomplete,Fig adds autocomplete to your terminal.,86,[TypeScript]
8,containers / podman,Podman: A tool for managing OCI containers and...,309,"[Go, Shell, Python, Perl, C, Makefile, Other]"
9,PeterL1n / RobustVideoMatting,"Robust Video Matting in PyTorch, TensorFlow, T...",Robust,[]
10,narze / THIS_REPO_HAS_1236_STARS,Click Star ⭐️ to see it in action,990,[JavaScript]
11,pedroslopez / whatsapp-web.js,A WhatsApp client library for NodeJS that conn...,42,"[JavaScript, Shell]"
12,doocs / advanced-java,😮 Core Interview Questions & Answers For Exper...,28,"[Java, JavaScript]"
13,TheAlgorithms / Javascript,A repository for All algorithms implemented in...,151,[JavaScript]
14,Universidade-Livre / ciencia-da-computacao,🎓 Um caminho para a educação autodidata em Ciê...,-,"[3, Camilo, de, matheusfelipeog, Felipe, Mateus]"
15,amark / gun,An open source cybersecurity protocol for sync...,116,"[JavaScript, HTML, Other]"
16,metaplex-foundation / metaplex,The Metaplex protocol,31,"[Rust, TypeScript, Less, JavaScript, Shell, Do..."
17,facebookincubator / Glean,"System for collecting, deriving and working wi...",9,"[Haskell, C++, Thrift, Yacc, Python, JavaScrip..."
18,NielsRogge / Transformers-Tutorials,This repository contains demos I made with the...,-,"[Jupyter, 100.0%]"
19,probml / pml-book,"""Probabilistic Machine Learning"" - a book seri...",2,"[Jupyter, 96.3%, 3.7%]"
20,nextcloud / server,"☁️ Nextcloud server, a safe home for all your ...",770,"[PHP, JavaScript, Vue, Gherkin, SCSS, Shell, O..."
21,dotnet / maui,".NET MAUI is the .NET Multi-platform App UI, a...",385,"[C#, HTML, PowerShell, CSS, Java, Shell]"
22,Alamofire / Alamofire,Elegant HTTP Networking in Swift,229,"[Swift, Ruby]"

6. Scrape the details of top 100 songs on billboard.com.

Url = https://www.billboard.com/

You have to find the following details:

A) Song name

B) Artist name

C) Last week rank

D) Peak rank

E) Weeks on board

Note: - From the home page you have to click on the charts option then hot 100-page link through code

In [46]:
#importing required libraries
import pandas as pd
import time
import selenium
from selenium import webdriver
from selenium.common.exceptions import NoSuchElementException, StaleElementReferenceException

In [92]:
# connect to the webdriver
driver = webdriver.Chrome(r"C:\Users\admin\Downloads\chromedriver_win32 (1)\chromedriver.exe")

In [93]:
url = "https://www.billboard.com/"
driver.get(url)

TimeoutException: Message: timeout: Timed out receiving message from renderer: 299.317
  (Session info: chrome=92.0.4515.159)

#### 7. Scrape the details of Data science recruiters from naukri.com.
Url = https://www.naukri.com/
You have to find the following details:
A) Name
B) Designation
C) Company
D) Skills they hire for
E) Location
Note: - From naukri.com homepage click on the recruit

In [53]:
# connect to the webdriver
driver = webdriver.Chrome(r"C:\Users\admin\Downloads\chromedriver_win32 (1)\chromedriver.exe")

In [54]:
url = "https://www.naukri.com/"
driver.get(url)

In [55]:
cli=driver.find_element_by_xpath("//ul[@class='midSec menu']/li[2]/a/div")
cli.click()

In [56]:
#get current window handle
p = driver.current_window_handle
#get first child window
chwnd = driver.window_handles
for w in chwnd:
   #switch focus to child window
   if(w!=p):
        driver.switch_to.window(w)
        break
time.sleep(2)

In [ ]:
#Now enter Data Sceience on serach field with send_keys option.

In [57]:
se=driver.find_element_by_xpath("//input[@class='sugInp']")
se.send_keys("Data science")

In [ ]:
#click on search button

In [59]:
bt=driver.find_element_by_id("qsbFormBtn")
bt.click()

In [ ]:
#Now we will scrap the required data.

In [60]:
name=driver.find_elements_by_xpath("//p[@class='highlightable']/a/span")
Name=[]
for i in name:
    Name.append(i.text)
Name

['Aakash Harit',
 'shravan Kumar Gaddam',
 'MARSIAN Technologies LLP',
 'Anik Agrawal',
 'subhas patel',
 'Abhishek - Only Analytics Hiring - India and',
 'Institute for Financial Management and Resear',
 'Balu Ramesh',
 'Asif Lucknowi',
 'InstaFinancials',
 'Priyanka Akiri',
 'Kalpana Dumpala',
 'Mubarak',
 'Kushal Rastogi',
 'Ruchi Dhote',
 'Mahesh Babu Channa',
 'Kapil Devang',
 'Manisha Yadav',
 'Riya Rajesh',
 'Rashmi Bhattacharjee',
 'Faizan Kareem',
 'Rithika dadwal',
 'Sandhya Khandagale',
 'Shaun Rao',
 'Azahar Shaikh',
 'Manas',
 'kumar',
 'Sunil Vedula',
 'Rajat Kumar',
 'Priya Khare',
 'Dhruv Dev Dubey',
 'Jayanth N',
 'SREEDHAR',
 'Ravi Dubey',
 'Radha Manivasagam',
 'Prateek Kumar',
 'Amit Sharma',
 'Kanan',
 'Shashikant Chaudhary',
 'Brad',
 'Rutuja Pawar',
 'Madhusudhan Sridhar',
 'Ankit Sinha',
 'Gaurav Chouhan',
 'Rashi Kacker',
 'Ashwini',
 'Balaji Kolli',
 'Rajani Nagaraj',
 'ROHIT Kumar',
 'Amir Chowdhury']

In [61]:
desg=driver.find_elements_by_xpath("//span[@class='ellipsis clr']")
Designation=[]
for i in desg:
    Designation.append(i.text)
Designation

['HR Manager',
 'Company Recruiter',
 'Company HR',
 'Company Recruiter',
 'Founder CEO',
 'Recruitment Lead Consultant',
 'Programme Manager',
 'HR Administrator',
 'Director',
 'Human Resource',
 'HR Manager',
 'Executive Hiring',
 'Company HR',
 'Company HR',
 'Senior Executive Talent Acquisition',
 'HR Team Lead',
 'HR Manager',
 'HR Executive',
 'Manager Talent Acquisition',
 'HR Head',
 'HR MANAGER',
 'HR Recruiter',
 'HR Recruiter',
 'Manager Human Resources',
 'Company Recruiter',
 'Lead Talent acquisition',
 'Proprietor',
 'CEO',
 'Founder CEO',
 'Senior Manager',
 'Company Recruitment Head',
 'Project Manager',
 'Recruitment Consultant',
 'Recruitment Manager',
 'HR Executive',
 'Head',
 'Consultant',
 'senior technology instructor',
 'HR Recruiter/HR Excutive',
 'Manager, Technical Recruiting',
 'Technical Recruiter',
 'Erp Implementer',
 'Head Analytics',
 'Chief Technical Officer',
 'Sr Product Manager',
 'Director Global Delivery',
 'Co Founder',
 'HR Manager',
 'Architect',
 'Managing Partner']

In [62]:
comp=driver.find_elements_by_xpath("//a[@class='ellipsis'][2]")
Company=[]
for i in comp:
    Company.append(i.text)
Company

['Data Science Network',
 'Shore Infotech India Pvt. Ltd',
 'MARSIAN Technologies LLP',
 'Enerlytics Software Solutions Pvt Ltd',
 'LibraryXProject',
 'Apidel Technologies Division of Transpower',
 'IFMR',
 'Techvantage Systems Pvt Ltd',
 'Weupskill- Live Wire India',
 'CBL Data Science Private Limited',
 'Infinitive Software Solutions Pvt.Ltd.',
 'Innominds Software',
 'MoneyTap',
 'QuantMagnum Technologies Pvt. Ltd.',
 'Bristlecone India Ltd',
 'SocialPrachar.com',
 'BISP Solutions',
 'Easi Tax',
 'Novelworx Digital Solutions',
 'AXESTRACK SOFTWARE SOLUTIONS PRIVATE...',
 'FirstTech Consaltants Pvt.Ltd',
 'Affine Analytics',
 'Compumatrice Multimedia Pvt Ltd',
 'Exela Technologies',
 'NEAL ANALYTICS SERVICES PVT LTD',
 'Autumn Leaf Consulting Services Private...',
 'trainin',
 'Nanoprecise Sci Corp',
 'R.S Consultancy &amp; Services',
 'Independent Consultant',
 'Confidential',
 'Dollarbird Information Services Pvt, Ltd',
 'JOBSMILL BUSINESS SOLUTIONS PRIVATE LIMITED',
 'HyrEzy Talent Solutions LLP',
 'Techcovery',
 'Trisect',
 'ASCO consulting',
 'NY INST',
 '3D India Staffing Research &amp; Consulting...',
 'O.C. Tanner',
 'Demand Matrix',
 'MADHUSUDHAN SRIDHAR',
 'Suntech Global',
 'Strategic Consulting Lab',
 'Impel Labs Pvt. Ltd.',
 'MRP Advisers',
 'Saras Solutions India Pvt Ltd',
 'WildJasmine',
 'LNT Private Limited',
 'Granular.ai']

In [63]:
skill=driver.find_elements_by_xpath("//div[@class='hireSec highlightable']")
Skills_required=[]
for i in skill:
    Skills_required.append(i.text)
Skills_required

['Classic ASP Developer, Internet Marketing Professional, Data Science SME, Content Writers, SEO Professional, Revenue Professional',
 '.Net, Java, Data Science, Linux Administration, Sql Server Development, Winforms, Wcf Services, Wpf, Telecom Engineering, Technical Management, Software',
 'Data Science, Artificial Intelligence, Machine Learning, Business Analytics',
 'Mean Stack, javascript, angularjs, mongodb, Web Services, rest, express, Node.js, Big Data, iot, Data Science, Cloud Computing, saas, Aws',
 'Hadoop, Spark, Digital Strategy, Data Architecture, Command Center, Cdp, Dmp, Kafka, Data Science, Data Analysis, Big Data Analytics, Real Time Analysis, SQL',
 'Analytics, Business Intelligence, Business Analytics, Predictive Modeling, Predictive Analytics, Data Science, Data Analysis, Data Analytics, Big Data, Big',
 'Data Science',
 'Machine Learning, algorithms, Go Getter, Computer Science, spark, Big Data, hdfs, sql, cassandra, hadoop, python, scala, java, Data Science, Front End',
 'Technical Training, Software Development, Presentation Skills, B.tech, M.tech, B.e., mca, msc, Computer Science, freshers, jobs in indore, Data Science, itil',
 'Software Development, It Sales, Account Management, Data Analysis, Customer Service, Sr, Software Engineering, Mvc, Ajax, Asp.net, Html, C#, Javascript',
 'Oracle Dba, Data Science, Data Warehousing, ETL, Jupyter, Numpy, Data Transformation, Snowflake, Teradata, Python, Data Manipulation, Relational Databases',
 'Qa, Ui/ux, Java Developer, Java Architect, C++/qt, Php, Lamp, Api, J2ee, Java, Soa, Esb, Middleware, Bigdata Achitect, Hadoop Architect, Deep',
 'Business Intelligence, Data Warehousing, Data Science, Business Analytics, Customer Support, Business Reporting, Bi',
 'Office Administration, Hr Administration, telecalling, client relationship management, Client Acquisition, Sales, Reception, HR, Recruitment, Onboarding, Human',
 'Qlikview, Qlik Sense, Microsoft Azure, Power Bi, Data Science, Machine Learning',
 'Social Media, digital media maketing, seo, smm, smo, sem, Content Wirting, social media marketing, social media manager, digital media marketing manager',
 'Big Data, Hadoop, Data Analytics, Data Science',
 'Telecalling, Client Interaction, Marketing, Research, Web Development, Social Media Marketing, Data Entry Operation, Excel, Ms Office, Invoicing',
 'Data Science',
 'Corporate Sales, Software Development, Software Sales, Marketing, Creative Designing, Corporate Planning, Senior Management, Crm, Client Relationship',
 'Data Analytics, Data Science, Machine Learning, Deep Learning, Nlp, Data Mining, Python, R, Database Administration, Text Mining',
 'Data Science, Machine Learning, Python, R, Deep Learning, Big Data, Hadoop',
 'Big Data, Data Science, Artificial Intelligence, Hadoop, Ui Development, Php, Freelancing, .Net, Software Testing, Sap, Leadership Hiring',
 'Java, Net, Angularjs, Hr, Infrastructure, Management, Project Management, Business Analysis, Data Science, Information Technology, Technology',
 'Data Science, Artificial Intelligence, Machine Learning, Data Analytics',
 'Software Architecture, Vp Engineering, Product Management, analytics, Data Science, Node.js, Principal Engineer, Big Data, python, angularjs, React.js',
 'Data Science, Hadoop, Rpas, Devops, Python, Aws, Teaching, Big Data',
 'Signal Processing, Machine Learning, Neural Networks, Data Science, Predictive Analytics, Time Series Analysis, Data Visualization, Technical Leadership, Data',
 'Web Technologies, Project Management, Software Architecture, Data Science, Object Oriented Programming, Computer Science, Electrical Engineering, Architecture',
 'Data Science, Artificial Intelligence, analytics, Business Intelligence, python, tableau, Power Bi, qlikview, sql, Data Warehousing, Data Visualization',
 'Server Administartion, Verilog, Vhdl, Digital Marketing, Market Research, Property Research, Legal, It And Non It Recruitment, Logistics, Supply Chain, Bfsi',
 'Data Analytics, Managed Services, Team Leading, python, Machine Learning, Google Analytics, Dmp, Aws, Campaign Analytics, Digital Campaigns, Audience',
 'Data Science, Machine Learning, Big Data Analytics, Spark, Python, R, Networking, Network Engineering, Placement, Training, Sql, Marketing, Mainframes, All',
 'Walmart Interra Skeps Expressstores indifi whitehatJr Practo Zylo Doctalk Medtrail',
 'Python, Artificial Intelligence, Machine Learning, Data Science',
 'Java, Python, Angularjs, Software Testing, Machine Learning, Data Science, Javascript, Django, React.js, Node.js, Augmented Reality, Virtual Reality, Advanced',
 'Machine Learning, Artificial Intelligence, Data Science, Software Engineering, Software Development, Graduate Engineer Trainee, Fresher, Data Analytics, Java',
 'C, C++, Artificial Intelligence, Python, Php, Web Development, Matlab, Data Science, Augmented Reality, C C++',
 'Relationship Management, Retail Sales, Private Banking, Mutual Funds, NISM, Equity, Finance, Financial Products, Financial Services, Verbal, Written',
 'Data Science, Software Engineering',
 'Data Science, Big Data Analytics, Digital Marketing, Content Writing, Ui Development, Database Development, Qa Automation, Python, Project Management',
 'Data Science, Recruitment, Salary',
 'B.Tech, Tableau, Statistics, R, Analytics, Time Series, Data Science, Business Solutions, SQL, Technical Skills, SSAS, SQL Server, Analysis Services, Qlikview',
 'Software Development, Business Intelligence, Big Data Analytics, Database Administration, Data Science, Microsoft Azure, Spark, Cassandra, Object Oriented',
 'Data Science, Node.js, Angularjs',
 'Data Science, Media Marketing, Resource Planning, Managed Services, Display Advertising, Machine Learning, Python, Etl, Sql',
 'Data Analysis, Learning, Data Science, Computer Science, Communication Skills',
 'Java, Hadoop, R, Machine Learning, Spark, Flume, Hdfs, Data Mining, Sas, Big, Data Science, Cloudera, Impala, Bigdata',
 'Software Development, Core Java, Unit Testing, Customer Experience, Problem Solving, Communication Skills, Mysql, Data Science, Sales Management, Analytics',
 'Machine Learning, Data Science, Product Management, New Product, Data Analysis, Computer Vision, Deep Learning, Python, Remote Sensing']

In [64]:
place=driver.find_elements_by_xpath("//small[@class='ellipsis']")
Location=[]
for i in place:
    Location.append(i.text)
Location

['Delhi',
 'Hyderabad / Secunderabad',
 'Pune',
 'Ahmedabad',
 'UK - (london)',
 'Vadodara / Baroda',
 'Chennai',
 'Trivandrum',
 'Indore',
 'Bengaluru / Bangalore',
 'Hyderabad',
 'Hyderabad / Secunderabad',
 'Bengaluru / Bangalore',
 'Mumbai',
 'Pune',
 'Hyderabad / Secunderabad',
 'Bhopal',
 'Navi Mumbai',
 'Cochin',
 'Delhi',
 'Hyderabad / Secunderabad',
 'Pune',
 'Pune',
 'Pune',
 'Pune',
 'Bengaluru / Bangalore',
 'Bengaluru / Bangalore',
 'Delhi',
 'Bengaluru / Bangalore',
 'Bengaluru / Bangalore',
 'Mysoru / Mysore',
 'Hyderabad / Secunderabad',
 'Ghaziabad',
 'Bengaluru / Bangalore',
 'Noida',
 'New Delhi',
 'Chennai',
 'Aligarh',
 'Salt Lake City',
 'Pune',
 'Bengaluru / Bangalore',
 'Mumbai',
 'Indore',
 'Bengaluru / Bangalore',
 'MYSORE',
 'Hyderabad / Secunderabad',
 'Bengaluru / Bangalore',
 'Mumbai']

8. Scrape the details of Highest selling novels.
Url = https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-greycompare/
You have to find the following details:
A) Book name
B) Author name
C) Volumes sold
D) Publisher
E) Genre

In [65]:
# connect to the webdriver
driver = webdriver.Chrome(r"C:\Users\admin\Downloads\chromedriver_win32 (1)\chromedriver.exe")

In [68]:
url = "https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare/"
driver.get(url)

In [ ]:
#Now we have to scrap data of highest selling Novels. On the website we can see that the data is tabular form.
#with the help of beautifulsoup we will extract the whole table.

In [69]:
soup = BeautifulSoup(driver.page_source, 'html')
tables = soup.find_all('table')

In [ ]:
#Now we will load the extracted data by using pandas.read_html(because it is is html format)

In [70]:
df = pd.read_html(str(tables))

In [71]:
df=df[0] #Here is the required data

In [72]:
df=df[0:100]
df

,Rank,Title,Author,Volume Sales,Publisher,Genre
0,1,"Da Vinci Code,The","Brown, Dan",5094805,Transworld,"Crime, Thriller & Adventure"
1,2,Harry Potter and the Deathly Hallows,"Rowling, J.K.",4475152,Bloomsbury,Children's Fiction
2,3,Harry Potter and the Philosopher's Stone,"Rowling, J.K.",4200654,Bloomsbury,Children's Fiction
3,4,Harry Potter and the Order of the Phoenix,"Rowling, J.K.",4179479,Bloomsbury,Children's Fiction
4,5,Fifty Shades of Grey,"James, E. L.",3758936,Random House,Romance & Sagas
...,...,...,...,...,...,...
95,96,"Ghost,The","Harris, Robert",807311,Random House,General & Literary Fiction
96,97,Happy Days with the Naked Chef,"Oliver, Jamie",794201,Penguin,Food & Drink: General
97,98,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne",792187,Scholastic Ltd.,Young Adult Fiction
98,99,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave",791507,Orion,Biography: General
99,100,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie",791095,Penguin,Food & Drink: General

In [ ]:
9. Scrape the details most watched tv series of all time from imdb.com.
 Url = https://www.imdb.com/list/ls095964455/
You have to find the following details:
A) Name
B) Year span
C) Genre
D) Run time
E) Ratings
F) Votes

In [73]:
# connect to the webdriver
driver = webdriver.Chrome(r"C:\Users\admin\Downloads\chromedriver_win32 (1)\chromedriver.exe")

In [74]:
url = "https://www.imdb.com/list/ls095964455/"
driver.get(url)

In [75]:
#Name of the series.
mov=driver.find_elements_by_xpath("//h3[@class='lister-item-header']/a")
Name=[]
for i in mov:
    Name.append(i.text)

In [76]:
#Year Span
year=driver.find_elements_by_xpath("//h3[@class='lister-item-header']/span[2]")
Year_span=[]
for i in year:
    Year_span.append(i.text)

In [77]:
#Genere
genere=driver.find_elements_by_xpath("//span[@class='genre']")
Genere=[]
for i in genere:
    Genere.append(i.text)

In [78]:
#Run Time
time=driver.find_elements_by_xpath("//span[@class='runtime']")
Run_Time=[]
for i in time:
    Run_Time.append(i.text)

In [79]:
#Ratings
rating=driver.find_elements_by_xpath("//div[@class='ipl-rating-star small']/span[2]")
Rating=[]
for i in rating:
    Rating.append(i.text)

In [80]:
#Votes
vot=driver.find_elements_by_name("nv")
Votes=[]
for i in vot:
    Votes.append(i.text)

In [81]:
imdb=pd.DataFrame({})
imdb['Name']=Name
imdb['Year_span']=Year_span
imdb['Genere']=Genere
imdb['Run_Time']=Run_Time
imdb['Rating']=Rating
imdb['Votes']=Votes
imdb

,Name,Year_span,Genere,Run_Time,Rating,Votes
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.2,"1,867,208"
1,Stranger Things,(2016– ),"Drama, Fantasy, Horror",51 min,8.7,"902,812"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,8.2,"894,437"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.6,"269,214"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"229,470"
...,...,...,...,...,...,...
95,Reign,(2013–2017),"Drama, Fantasy",42 min,7.5,"45,479"
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"56,356"
97,Criminal Minds,(2005–2020),"Crime, Drama, Mystery",42 min,8,"174,334"
98,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45 min,7.1,"36,480"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"198,160"

In [ ]:
10. Details of Datasets from UCI machine learning repositories.
 Url = https://archive.ics.uci.edu/
 You have to find the following details:
A) Dataset name
B) Data type
C) Task
D) Attribute type
E) No of instances
F) No of attribute
G) Year
Note: - from the home page you have to go to the Show All Dataset page through code.

In [82]:
# connect to the webdriver
driver = webdriver.Chrome(r"C:\Users\admin\Downloads\chromedriver_win32 (1)\chromedriver.exe")

In [83]:
url = "https://archive.ics.uci.edu/"
driver.get(url)

In [ ]:
#from the home page we have to select the Show All Dataset page.

In [84]:
ber=driver.find_element_by_xpath("//span[@class='normal']/b/a")
ber.click()

In [ ]:
#Lets the extract the required data

In [85]:
#DataSet_Name
Name=driver.find_elements_by_xpath("//p[@class='normal']/b/a")
DataSet_Name=[]
for i in Name:
    DataSet_Name.append(i.text)

In [86]:
#Year
year=driver.find_elements_by_xpath("//td[7]/p[@class='normal']")
Year=[]
for i in year:
    Year.append(i.text)

In [87]:
#For the remaining data we will use exception.
Data_type=[]
Task=[]
Attribute_type=[]
No_of_instances=[]
No_of_attribute=[]

In [ ]:
#first we will get the urls of each data set.

In [88]:
ur=driver.find_elements_by_xpath("//p[@class='normal']/b/a")
url=[]
for i in ur:
    url.append(i.get_attribute('href'))

In [89]:
len(url)

588

In [ ]:
#Now we will handle the remaining data with exception.

In [90]:
for i in url:
    driver.get(i)
    
    try:
        noof=driver.find_element_by_xpath("//tr[1]/td[2]/p[@class='normal']")
        Data_type.append(noof.text)
    except NoSuchElementException:
        Data_type.append("-")
    try:
        ret=driver.find_element_by_xpath("//tr[1]/td[4]/p[@class='normal']")
        No_of_instances.append(ret.text)
    except NoSuchElementException:
        No_of_instances.append("-")      
        
    try:
        oof=driver.find_element_by_xpath("//tr[3]/td[2]/p[@class='normal']")
        Task.append(oof.text)
    except NoSuchElementException:
        Task.append("-")
    try:
        et=driver.find_element_by_xpath("//tr[2]/td[2]/p[@class='normal']")
        Attribute_type.append(et.text)
    except NoSuchElementException:
        Attribute_type.append("-") 
        
    try:
        vt=driver.find_element_by_xpath("//tr[2]/td[4]/p[@class='normal']")
        No_of_attribute.append(vt.text)
    except NoSuchElementException:
        No_of_attribute.append("-")

In [ ]:
#Now let's create data frame for all scrapped data.

In [91]:
UCI=pd.DataFrame({})
UCI['DataSet_Name']=DataSet_Name
UCI['Data_type']=Data_type
UCI['Task']=Task
UCI['Attribute_type']=Attribute_type
UCI['No_of_instances']=No_of_instances
UCI['No_of_attribute']=No_of_attribute
UCI['Year']=Year
UCI

,DataSet_Name,Data_type,Task,Attribute_type,No_of_instances,No_of_attribute,Year
0,Abalone,Multivariate,Classification,"Categorical, Integer, Real",4177,8,1995
1,Adult,Multivariate,Classification,"Categorical, Integer",48842,14,1996
2,Annealing,Multivariate,Classification,"Categorical, Integer, Real",798,38,
3,Anonymous Microsoft Web Data,N/A,Recommender-Systems,Categorical,37711,294,1998
4,Arrhythmia,Multivariate,Classification,"Categorical, Integer, Real",452,279,1998
...,...,...,...,...,...,...,...
583,in-vehicle coupon recommendation,Multivariate,Classification,N/A,12684,23,2020
584,Gait Classification,Multivariate,Classification,Real,48,321,2020
585,Wikipedia Math Essentials,Time-Series,Regression,Real,731,1068,2021
586,Wikipedia Math Essentials,Time-Series,Regression,Real,731,1068,2021
587,Synchronous Machine Data Set,Multivariate,Regression,Real,557,5,2021